### PR TITLE
Add support for arrays

### PR DESCRIPTION
**Pull request by sharshenov**
Hello,
It would be great to have support for text arrays as well. What do you think?

### CODE REVIEW

**Comment by sharshenov** [comment]
@holli I'm sorry for tagging you, but maybe this feature will be helpful for those who use [Rails/Postgres `array` attributes](https://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html)

**Comment by holli** [comment]
Seems smart :) 

I haven't used those arrays myself. What is your usecase? 

I tried to think is there any downsides or is someone trusting the way it previously worked. Only thing that came to my mind is that if someone is using :nullify to make sure that empty arrays are translated to null, not maybe such a common usecase. The pull request seems like the right way to go.

Few things:

- [ ] 1. Any ideas: in most cases do we want to get null or empty list if there are no items in the list?
- [ ] 2. Adding a bit more complicated test:
   -  `@record.foo = [" aaa \t", "  "]`   => to ['aaa', nil] or maybe better ['aaa']
   - So what to do when one of the items goes to null. Should it call maybe `compact` at the end to remove empty things from the list. (Refactoring the ifelse thingie to multiple lines)
- [ ] version bump to 2.6 and info to changelog

**Comment by sharshenov** [comment]
Great :+1:  I'll do it when I have free time (ETA 1-2 weeks)

**Comment by sharshenov** [comment]
@holly 

> I haven't used those arrays myself. What is your usecase?

I have a crawler that fetches web-pages, parses data (including tags **arrays**) and stores this data in DB. Other component later processes this data. I use `auto_strip_attributes` for all parsed attributes and lack of support for `array` string attributes inspired me to make this PR.


> Any ideas: in most cases do we want to get null or empty list if there are no items in the list?

Well, this a good question.
From one hand, value `[]` is more "array-friendly" than `nil`. From another hand, `nil` value in database is more close to `:nullify` option meaning. Especially if `:nullify` option of `auto_strip_attributes` sets empty strings values to `nil`. So I'd say that "`nil` approach" is more **expected**.
But a developer might want not to drop empty strings in array **and** not nullify it. For example, here is a DB schema that demonstrates situation when code expects `roles` to always be an array:
```ruby
create_table "users", force: :cascade do |t|
  t.string "roles", default: [], null: false, array: true
end
```

I've added `:nullify_array` option (with default value `true`) to support "array-friendly" approach. So we cover both cases.

**Comment by holli** [comment]
Yay thanks. ;erged and released new version to rubygems

**Pull request merged**
